### ISSUE TITLE
IP address and mac address info

### ISSUE THREAD

**Issue by dnayr81** [kolide/kolide-quickstart#32]
Hey Guys,

is there a way that we can add info for Windows IP and Mac address on kolide, somehow it is not showing on the hosts page. In any case I missed something in relation how to enable this please let me know.

**Comment by marpaia** [comment]
Hey @dnayr81. The reason why IP address is not included is because the interface_details table does not include `ipackets` and `opackets` for each interface, so it's difficult (impossible?) for us to determine which interface is the "main" interface. So even though we can get the IP and MAC for ALL interfaces, we can't calculate which to display. 

I created an issue for this a few weeks ago and I'm hoping to be able to spend some time on it soon: https://github.com/facebook/osquery/issues/2907

If you had a different cross-platform query that could retrieve this information without needing those fields, we could update that on the Kolide backend, but I'm not sure of one off the top of my head.
